"""classroom_and_lix_score

Revision ID: 04c6f85ffc86
Revises: 640e40e6aac3
Create Date: 2026-05-21 23:14:15.720143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c6f85ffc86'
down_revision = '640e40e6aac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('child_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('invite_code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_log_entry', sa.Boolean(), nullable=False),
    sa.Column('series_part', sa.Integer(), nullable=True),
    sa.Column('strategy_used', sa.String(length=50), nullable=True),
    sa.Column('parent_story_id', sa.Integer(), nullable=True),
    sa.Column('root_story_id', sa.Integer(), nullable=True),
    sa.Column('problem_name', sa.String(length=150), nullable=True),
    sa.Column('problem_category', sa.String(length=150), nullable=True),
    sa.Column('problem_influence', sa.Text(), nullable=True),
    sa.Column('unique_outcome', sa.Text(), nullable=True),
    sa.Column('discovered_method_name', sa.String(length=150), nullable=True),
    sa.Column('strength_type', sa.String(length=150), nullable=True),
    sa.Column('discovered_method_steps', sa.Text(), nullable=True),
    sa.Column('child_values', sa.Text(), nullable=True),
    sa.Column('support_system', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('progress_before', sa.Integer(), nullable=True),
    sa.Column('progress_after', sa.Integer(), nullable=True),
    sa.Column('lix_score_stored', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['root_story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['student_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'student_user_id')
    )
    op.create_table('profile_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_result')
    op.drop_table('profile_relation')
    op.drop_table('profile_attribute')
    op.drop_table('classroom_student')
    op.drop_table('story')
    op.drop_table('classroom')
    op.drop_table('child_profile')
    op.drop_table('user')
    # ### end Alembic commands ###
