"""Add child profile models

Revision ID: 640e40e6aac3
Revises: 76df432865d1
Create Date: 2025-06-12 21:56:21.121428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640e40e6aac3'
down_revision = '76df432865d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'story', 'story', ['root_story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_table('profile_relation')
    op.drop_table('profile_attribute')
    op.drop_table('child_profile')
    # ### end Alembic commands ###
