"""Add root_story_id and strategy_used to Story model

Revision ID: 76df432865d1
Revises: afde826de25f
Create Date: 2025-06-11 10:43:49.286041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76df432865d1'
down_revision = 'afde826de25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('strategy_used', sa.String(length=50), nullable=True))
    op.add_column('story', sa.Column('root_story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'story', 'story', ['root_story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_column('story', 'root_story_id')
    op.drop_column('story', 'strategy_used')
    # ### end Alembic commands ###
