"""add role and password_hash to user

Revision ID: 9ab97c032834
Revises: 
Create Date: 2025-06-01 20:21:50.310342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab97c032834'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False, server_default='free'))
    op.add_column('user', sa.Column('password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
