"""Add problem_category and strength_type to Story model

Revision ID: afde826de25f
Revises: e7b9f1533868
Create Date: 2025-06-11 09:46:18.968418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afde826de25f'
down_revision = 'e7b9f1533868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('problem_category', sa.String(length=150), nullable=True))
    op.add_column('story', sa.Column('strength_type', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'strength_type')
    op.drop_column('story', 'problem_category')
    # ### end Alembic commands ###
