"""Add Story model for Logbook

Revision ID: e7b9f1533868
Revises: 9ab97c032834
Create Date: 2025-06-10 11:00:16.056836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b9f1533868'
down_revision = '9ab97c032834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - manually adjusted ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_log_entry', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('series_part', sa.Integer(), nullable=True, server_default=sa.text('1')),
    sa.Column('parent_story_id', sa.Integer(), nullable=True),
    sa.Column('problem_name', sa.String(length=150), nullable=True),
    sa.Column('problem_influence', sa.Text(), nullable=True),
    sa.Column('unique_outcome', sa.Text(), nullable=True),
    sa.Column('discovered_method_name', sa.String(length=150), nullable=True),
    sa.Column('discovered_method_steps', sa.Text(), nullable=True),
    sa.Column('child_values', sa.Text(), nullable=True),
    sa.Column('support_system', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('progress_before', sa.Integer(), nullable=True),
    sa.Column('progress_after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - manually adjusted ###
    op.drop_table('story')
    # ### end Alembic commands ###